services:
  mc-mod-server:
    container_name: mc-mod-server
    build: .
    restart: always
    init: true
    healthcheck:
      interval: 10s
      timeout: 2s
      test: lsof -i :3621 || exit 1
    networks:
      default:
        ipv4_address: 172.19.1.6
    hostname: "mc-mods.containers.local"
    labels:
      - "hostname=mc-mods.containers.local"

networks:
  default:
    name: mc-mod-server
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.1.8/30
    driver_opts:
      com.docker.network.bridge.name: br-mc-mod-server
